### ISSUE TITLE
License - MIT vs GPL

### ISSUE THREAD

**Issue by Woren** [KhubaibKhan4/MediaPlayer-KMP#26]
I want to be sure about license used for this project which is now [MIT](https://github.com/KhubaibKhan4/MediaPlayer-KMP/blob/master/LICENSE). 

For desktop part (MediaPlayer) is used JavaFX which is based on [GNU GPL 2.0 license](https://github.com/openjdk/jfx/blob/master/LICENSE). I'm not quite sure if this MediaPlayer library should also have GPL or can have MIT license. 

I just to be sure if I will use this library in my project because GPL license is strict about closed source projects. 

Thank you for answer and great work with this library!

**Comment by KhubaibKhan4** [comment]
Thank you for your concern about the licence. The licence will be MIT. You didn't need to worry about it. Make sure to provide feedback as well. Thank you 🙏

**Comment by KhubaibKhan4** [comment]
@Woren Thank you for your suggestions. I just updated the License to GNU GPL 2.0 license due to JavaFx.

**Comment by Woren** [comment]
No problem, I wasn't sure myself. Thank you for double checking it. Feel free to close this issue.

FYI - Here is the [list ](https://stackoverflow.com/questions/75064763/how-to-play-audio-in-kotlin-multiplatform-desktop/77718818#77718818) of other java / kotlin / KMP audio libraries which can be possibly used and license can be more open.

**Comment by KhubaibKhan4** [comment]
Thank you. I really appreciate it.
