### ISSUE TITLE
MediaPlayer only works if URL ends with ".mp3"

### ISSUE THREAD

**Issue by slickorange** [KhubaibKhan4/MediaPlayer-KMP#27]
My server returns media files with a url which looks something like this: http://10.0.0.108:8081/nodes/8d6b8364-cbd2-4a22-bc8b-092ab6732436/media

This is a problem because it seems the MediaPlayer only works if the url ends with ".mp3"

**Comment by KhubaibKhan4** [comment]
You must need to provide a valid URL with an extension like .mp3

**Comment by slickorange** [comment]
My URL is valid and streaming the file works in any browser. My server is designed to hide the file details from the URL (a common requirement) - the client only provides the file uuid and the server responds with the file (which could be video, mp3 etc..) So unfortunately that makes this component unusable in that case

**Comment by KhubaibKhan4** [comment]
@slickorange Thank you for creating this issue. I just fixed this issue and updating the latest version on the Maven Central.
