### ISSUE TITLE
Support timestamp in a youtube video

### ISSUE THREAD

**Issue by celcius112** [KhubaibKhan4/MediaPlayer-KMP#33]
At the moment, the YoutubePlayer does not support timestamps, i.e.: given `https://youtu.be/3i1YzKNGKro?t=1`, starting the video at the 1 second mark. 

My first thought was to implement a trivial extractor using a regex. Having done that, I found out that it is not as trivial as expected for the JVM module: the video will appear and will be interactable, but will never start.

**Comment by KhubaibKhan4** [comment]
Thank you for your suggestions. I'll definitely add in the upcoming updates.

**Comment by KhubaibKhan4** [comment]
@celcius112 Thank you for your suggestion. I just added your recommendations and updating the latest version on the Maven Central.
