### ISSUE TITLE
Youtube Player and ExoPlayer are not optimized for LazyLists

### ISSUE THREAD

**Issue by Vaibhav2002** [KhubaibKhan4/MediaPlayer-KMP#36]
Both YoutubePlayer and ExoPlayer VideoPlayer is using the incorrect `AndroidView` overload which makes it not lazyList friendly, it will recreate everytime the LazyList items comes into composition

Instead this overload of `AndroidView` must be used
https://developer.android.com/develop/ui/compose/migrate/interoperability-apis/views-in-compose#androidview_in_lazy_lists

**Comment by KhubaibKhan4** [comment]
Thank you for your suggestion. You're right but you can use the VideoPlayer inside the LazyList. In the upcoming updates, I'm provide the callbacks as well as the ReelViews for the Videos as well.

**Comment by KhubaibKhan4** [comment]
Just Fixed the issues and Updating the latest version to maven central. If you've any suggestions, Please let me know.
