### ISSUE TITLE
Unable to play audio streaming

### ISSUE THREAD

**Issue by tawhidmonowar** [KhubaibKhan4/MediaPlayer-KMP#56]
Here some radio streaming url : 

- http://209.126.105.44:8000/stream
- http://icecast.radiofrance.fr/franceinter-hifi.aac
- http://st01.dlf.de/dlf/01/128/mp3/stream.mp3

MediaPlayer unable to play any streaming url on android, and only mp3 url can play on desktop (windows)

**Comment by KhubaibKhan4** [comment]
@tawhidmonowar Thank you for reporting an issue. I'll add streaming links asap. If you do have any other suggestions, please let me know.
