### ISSUE TITLE
Auth - How to add a token to the request

### ISSUE THREAD

**Issue by 0verEngineer** [KhubaibKhan4/MediaPlayer-KMP#65]
Hey, i would like to use this library but i need to add a bearer token to the audio file requests, is this possible?

It would be even better to allow adding of custom headers.

Thanks a lot

**Comment by KhubaibKhan4** [comment]
Thank you for your suggestion. I'll try to add Bearer Token support in the next update. If you do have any other suggestions, please let me know. Thank you

**Comment by 0verEngineer** [comment]
Thabk you, i would suggest to add support for adding headers to the request, not only a token parameter or something, so there can be added any headers that are needed.
